branch-defaults:
  master:
    environment: consensus-dev
global:
  application_name: consensus
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2014.03 v1.1.0 running Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
