# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('rank', models.FloatField(default=0.5)),
                ('num_up', models.IntegerField(default=0)),
                ('num_dw', models.IntegerField(default=0)),
                ('num_xx', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-rank'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Bundle')),
            ],
        ),
        migrations.CreateModel(
            name='BundleVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('choice', models.CharField(choices=[('up', 'up'), ('dw', 'dw'), ('xx', 'xx')], default='xx', max_length=2)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Bundle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('rank', models.FloatField(default=0.5)),
                ('num_up', models.IntegerField(default=0)),
                ('num_dw', models.IntegerField(default=0)),
                ('num_xx', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncomments', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('rank', models.FloatField(default=0.5)),
                ('num_up', models.IntegerField(default=0)),
                ('num_dw', models.IntegerField(default=0)),
                ('num_xx', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-rank'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacetVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('choice', models.CharField(choices=[('up', 'up'), ('dw', 'dw'), ('xx', 'xx')], default='xx', max_length=2)),
                ('Facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Facet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('rank', models.FloatField(default=0.5)),
                ('num_up', models.IntegerField(default=0)),
                ('num_dw', models.IntegerField(default=0)),
                ('num_xx', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-rank'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralFacet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Facet')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.General')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('choice', models.CharField(choices=[('up', 'up'), ('dw', 'dw'), ('xx', 'xx')], default='xx', max_length=2)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.General')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('rank', models.FloatField(default=0.5)),
                ('num_up', models.IntegerField(default=0)),
                ('num_dw', models.IntegerField(default=0)),
                ('num_xx', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('rank', models.FloatField(default=0.5)),
                ('num_up', models.IntegerField(default=0)),
                ('num_dw', models.IntegerField(default=0)),
                ('num_xx', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-rank'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificFacet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Facet')),
                ('specific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Specific')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('choice', models.CharField(choices=[('up', 'up'), ('dw', 'dw'), ('xx', 'xx')], default='xx', max_length=2)),
                ('specific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Specific')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='specificvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consensus.User'),
        ),
        migrations.AddField(
            model_name='specific',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.User'),
        ),
        migrations.AddField(
            model_name='specific',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.Discussion'),
        ),
        migrations.AddField(
            model_name='specific',
            name='facets',
            field=models.ManyToManyField(through='consensus.SpecificFacet', to='consensus.Facet'),
        ),
        migrations.AddField(
            model_name='specific',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.General'),
        ),
        migrations.AddField(
            model_name='specific',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sproject', to='consensus.Project'),
        ),
        migrations.AddField(
            model_name='specific',
            name='votes',
            field=models.ManyToManyField(related_name='svotes', through='consensus.SpecificVote', to='consensus.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.Discussion'),
        ),
        migrations.AddField(
            model_name='generalvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consensus.User'),
        ),
        migrations.AddField(
            model_name='general',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.User'),
        ),
        migrations.AddField(
            model_name='general',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.Discussion'),
        ),
        migrations.AddField(
            model_name='general',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gproject', to='consensus.Project'),
        ),
        migrations.AddField(
            model_name='general',
            name='votes',
            field=models.ManyToManyField(related_name='gvotes', through='consensus.GeneralVote', to='consensus.User'),
        ),
        migrations.AddField(
            model_name='facetvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consensus.User'),
        ),
        migrations.AddField(
            model_name='facet',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.User'),
        ),
        migrations.AddField(
            model_name='facet',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.Discussion'),
        ),
        migrations.AddField(
            model_name='facet',
            name='general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.General'),
        ),
        migrations.AddField(
            model_name='facet',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fproject', to='consensus.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.Discussion'),
        ),
        migrations.AddField(
            model_name='bundlevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consensus.User'),
        ),
        migrations.AddField(
            model_name='bundlegeneral',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.General'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.User'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus.Discussion'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='generals',
            field=models.ManyToManyField(through='consensus.BundleGeneral', to='consensus.General'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bproject', to='consensus.Project'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='votes',
            field=models.ManyToManyField(related_name='bvotes', through='consensus.BundleVote', to='consensus.User'),
        ),
    ]
