# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consensus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ['-rank', 'id']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-rank', 'id']},
        ),
        migrations.AlterModelOptions(
            name='facet',
            options={'ordering': ['-rank', 'id']},
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'ordering': ['-rank', 'id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-rank', 'id']},
        ),
        migrations.AlterModelOptions(
            name='specific',
            options={'ordering': ['-rank', 'id']},
        ),
    ]
