# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consensus', '0002_auto_20160805_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Comment')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus.Discussion')),
            ],
        ),
    ]
